### ISSUE TITLE
Add a tunnel to the model

### ISSUE THREAD

**Issue by Wh20-fly** [danielsk78/Hydraulic_Press_Controller_RPi#1]
Hi, @danielsk78 
I want to add a tunnel to the model like the following photo you made,could you upload the code making the photo,I want to use that for reference,thank you very much,looking forward your reply,I am really eager to get taht code.
![81466324-fea9fe00-91d0-11ea-83ac-9a7f311ae395](https://user-images.githubusercontent.com/60054308/81519520-24233d00-9374-11ea-88f9-e824d052aec4.png)

**Comment by danielsk78** [comment]
Dear @wh19971014 
Please abstain of creating issues of other repositories outside of their respective space. Contributions to this repository should follow the GitHub Community Guidelines.
